
let a = 5;
//let b = 0;

try{
    let div = a/b;
    console.log(div);
}catch(err){
    console.log("Error occured :",err);
}
